services:
  svr_n8n:
    image: n8nio/n8n
    container_name: cont_n8n
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
    ports:
      - "5678:5678"
    volumes:
      - /root/vol_n8n:/home/node/.n8n
